selected_scheme scheme-full
TEXDIR /usr/local/texlive/2026
TEXMFCONFIG ~/.texlive2026/texmf-config
TEXMFHOME ~/texmf
TEXMFLOCAL /usr/local/texlive/texmf-local
TEXMFSYSCONFIG /usr/local/texlive/2026/texmf-config
TEXMFSYSVAR /usr/local/texlive/2026/texmf-var
TEXMFVAR ~/.texlive2026/texmf-var
option_doc 0
option_src 0
