selected_scheme scheme-full
TEXDIR /usr/local/texlive/2021
TEXMFCONFIG ~/.texlive2021/texmf-config
TEXMFHOME ~/texmf
TEXMFLOCAL /usr/local/texlive/texmf-local
TEXMFSYSCONFIG /usr/local/texlive/2021/texmf-config
TEXMFSYSVAR /usr/local/texlive/2021/texmf-var
TEXMFVAR ~/.texlive2021/texmf-var
option_doc 0
option_src 0
