name: Build Docker images
on:
  push:
    branches:
      - '!main'
      - 'testing/**'
      - 'feature/**'
      - 'hotfix/**'

jobs:
  build-base:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build base
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: maxkratz/texlive:base
          platforms: linux/amd64,linux/arm64,linux/arm/v7

  build-image:
    runs-on: [ubuntu-22.04]
    needs: [build-base]
    timeout-minutes: 720
    strategy:
      matrix:
        year: [2017, 2018, 2019, 2020, 2021, 2022, 2023]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.year }}
          push: false
          tags: maxkratz/texlive:${{ matrix.year }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7

  build-image-variants:
    # Use a self-hosted runner to circumvent the small storage size of GitHub-hosted runners
    runs-on: [self-hosted]
    needs: [build-image]
    strategy:
      matrix:
        year: [2022-gradle, 2023-gradle, 2023-python, 2024-gradle, 2024-python]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.year }}
          push: false
          tags: maxkratz/texlive:${{ matrix.year }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7

  # latest is an extra build step because of buggy GitHub Actions if conditions
  build-latest-image:
    runs-on: [ubuntu-22.04]
    needs: [build-base]
    timeout-minutes: 720
    strategy:
      matrix:
        year: [2024]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build latest image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.year }}
          push: false
          tags: |
            maxkratz/texlive:${{ matrix.year }}
            maxkratz/texlive:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7

  # 2016 can not be built with arm64 support
  build-2016-image:
    runs-on: [ubuntu-22.04]
    needs: [build-base]
    timeout-minutes: 720
    strategy:
      matrix:
        year: [2016]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.year }}
          push: false
          tags: maxkratz/texlive:${{ matrix.year }}
          platforms: linux/amd64,linux/arm/v7
